package jano.main;

import jano.builder.adapters.TurtleAdapter;
import jano.builder.exceptions.ReaderException;

public class Main4 {

	static String model = ""
			+ "@prefix : <https://auroral.iot.linkeddata.es/def/tourism#> .\n"
			+ "@prefix owl: <http://www.w3.org/2002/07/owl#> .\n"
			+ "@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .\n"
			+ "@prefix xml: <http://www.w3.org/XML/1998/namespace> .\n"
			+ "@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .\n"
			+ "@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .\n"
			+ "@base <https://auroral.iot.linkeddata.es/def/tourism#> .\n"
			+ "\n"
			+ "<https://auroral.iot.linkeddata.es/def/tourism#> rdf:type owl:Ontology ;\n"
			+ "                                                  <http://purl.org/dc/terms/creator> \"Andrea Cimmino\" ,\n"
			+ "                                                                                     \"Juan Cano\" ,\n"
			+ "                                                                                     \"MarÃ­a Poveda-VillalÃ³n\" ,\n"
			+ "                                                                                     \"RaÃºl Garcia-Castro\" ;\n"
			+ "                                                  owl:versionInfo \"0.0.1\" .\n"
			+ "\n"
			+ "#################################################################\n"
			+ "#    Annotation properties\n"
			+ "#################################################################\n"
			+ "\n"
			+ "###  http://purl.org/dc/terms/creator\n"
			+ "<http://purl.org/dc/terms/creator> rdf:type owl:AnnotationProperty .\n"
			+ "\n"
			+ "\n"
			+ "#################################################################\n"
			+ "#    Datatypes\n"
			+ "#################################################################\n"
			+ "\n"
			+ "###  http://www.w3.org/2001/XMLSchema#date\n"
			+ "xsd:date rdf:type rdfs:Datatype .\n"
			+ "\n"
			+ "\n"
			+ "#################################################################\n"
			+ "#    Object Properties\n"
			+ "#################################################################\n"
			+ "\n"
			+ "###  http://purl.org/dc/terms/language\n"
			+ "<http://purl.org/dc/terms/language> rdf:type owl:ObjectProperty ;\n"
			+ "                                    rdfs:label \"language\" .\n"
			+ "\n"
			+ "\n"
			+ "###  http://www.w3.org/2003/01/geo/wgs84_pos#location\n"
			+ "<http://www.w3.org/2003/01/geo/wgs84_pos#location> rdf:type owl:ObjectProperty ;\n"
			+ "                                                   rdfs:label \"location\" .\n"
			+ "\n"
			+ "\n"
			+ "###  http://xmlns.com/foaf/0.1/depiction\n"
			+ "<http://xmlns.com/foaf/0.1/depiction> rdf:type owl:ObjectProperty ;\n"
			+ "                                      rdfs:label \"depiction\" .\n"
			+ "\n"
			+ "\n"
			+ "###  https://auroral.iot.linkeddata.es/def/tourism#coverImage\n"
			+ ":coverImage rdf:type owl:ObjectProperty ;\n"
			+ "            rdfs:domain :Activity ;\n"
			+ "            rdfs:range <http://xmlns.com/foaf/0.1/Image> ;\n"
			+ "            rdfs:label \"cover image\" .\n"
			+ "\n"
			+ "\n"
			+ "###  https://auroral.iot.linkeddata.es/def/tourism#hasStartingPrice\n"
			+ ":hasStartingPrice rdf:type owl:ObjectProperty ;\n"
			+ "                  rdfs:domain :Activity ;\n"
			+ "                  rdfs:range :Price ;\n"
			+ "                  rdfs:label \"has starting price\" .\n"
			+ "\n"
			+ "\n"
			+ "###  https://auroral.iot.linkeddata.es/def/tourism#inCurrency\n"
			+ ":inCurrency rdf:type owl:ObjectProperty ;\n"
			+ "            rdfs:domain :Price ;\n"
			+ "            rdfs:range :Currency ;\n"
			+ "            rdfs:label \"in currency\" .\n"
			+ "\n"
			+ "\n"
			+ "###  https://auroral.iot.linkeddata.es/def/tourism#mapPoint\n"
			+ ":mapPoint rdf:type owl:ObjectProperty ;\n"
			+ "          rdfs:domain :Activity ;\n"
			+ "          rdfs:range <http://xmlns.com/foaf/0.1/Image> ,\n"
			+ "                     :ActivityDifficulty ;\n"
			+ "          rdfs:label \"map point\" .\n"
			+ "\n"
			+ "\n"
			+ "###  https://auroral.iot.linkeddata.es/def/tourism#postedToChannel\n"
			+ ":postedToChannel rdf:type owl:ObjectProperty ;\n"
			+ "                 rdfs:domain :Activity ;\n"
			+ "                 rdfs:range :Channel ;\n"
			+ "                 rdfs:label \"posted to channel\" .\n"
			+ "\n"
			+ "\n"
			+ "#################################################################\n"
			+ "#    Data properties\n"
			+ "#################################################################\n"
			+ "\n"
			+ "###  http://purl.org/dc/terms/description\n"
			+ "<http://purl.org/dc/terms/description> rdf:type owl:DatatypeProperty ;\n"
			+ "                                       rdfs:domain :Activity ;\n"
			+ "                                       rdfs:range xsd:string ;\n"
			+ "                                       rdfs:label \"description\" .\n"
			+ "\n"
			+ "\n"
			+ "###  http://purl.org/dc/terms/lastModified\n"
			+ "<http://purl.org/dc/terms/lastModified> rdf:type owl:DatatypeProperty ;\n"
			+ "                                        rdfs:label \"last modified\" .\n"
			+ "\n"
			+ "\n"
			+ "###  http://purl.org/dc/terms/rights\n"
			+ "<http://purl.org/dc/terms/rights> rdf:type owl:DatatypeProperty ;\n"
			+ "                                  rdfs:label \"rights\" .\n"
			+ "\n"
			+ "\n"
			+ "###  http://purl.org/dc/terms/title\n"
			+ "<http://purl.org/dc/terms/title> rdf:type owl:DatatypeProperty ;\n"
			+ "                                 rdfs:label \"title\" .\n"
			+ "\n"
			+ "\n"
			+ "###  http://www.w3.org/2003/01/geo/wgs84_pos#alt\n"
			+ "<http://www.w3.org/2003/01/geo/wgs84_pos#alt> rdf:type owl:DatatypeProperty ;\n"
			+ "                                              rdfs:label \"alt\" .\n"
			+ "\n"
			+ "\n"
			+ "###  http://www.w3.org/2003/01/geo/wgs84_pos#lat\n"
			+ "<http://www.w3.org/2003/01/geo/wgs84_pos#lat> rdf:type owl:DatatypeProperty ;\n"
			+ "                                              rdfs:label \"lat\" .\n"
			+ "\n"
			+ "\n"
			+ "###  http://www.w3.org/2003/01/geo/wgs84_pos#long\n"
			+ "<http://www.w3.org/2003/01/geo/wgs84_pos#long> rdf:type owl:DatatypeProperty ;\n"
			+ "                                               rdfs:label \"long\" .\n"
			+ "\n"
			+ "\n"
			+ "###  https://auroral.iot.linkeddata.es/def/tourism#amount\n"
			+ ":amount rdf:type owl:DatatypeProperty ;\n"
			+ "        rdfs:domain :Price ;\n"
			+ "        rdfs:label \"amount\" .\n"
			+ "\n"
			+ "\n"
			+ "###  https://auroral.iot.linkeddata.es/def/tourism#channelName\n"
			+ ":channelName rdf:type owl:DatatypeProperty ;\n"
			+ "             rdfs:domain :Channel ;\n"
			+ "             rdfs:range xsd:string ;\n"
			+ "             rdfs:label \"channel name\" .\n"
			+ "\n"
			+ "\n"
			+ "###  https://auroral.iot.linkeddata.es/def/tourism#endDate\n"
			+ ":endDate rdf:type owl:DatatypeProperty ;\n"
			+ "         rdfs:range xsd:date ;\n"
			+ "         rdfs:label \"end date\" .\n"
			+ "\n"
			+ "\n"
			+ "###  https://auroral.iot.linkeddata.es/def/tourism#externalBookingURL\n"
			+ ":externalBookingURL rdf:type owl:DatatypeProperty ;\n"
			+ "                    rdfs:domain :Activity ;\n"
			+ "                    rdfs:label \"external booking u r l\" .\n"
			+ "\n"
			+ "\n"
			+ "###  https://auroral.iot.linkeddata.es/def/tourism#hiddenDescription\n"
			+ ":hiddenDescription rdf:type owl:DatatypeProperty ;\n"
			+ "                   rdfs:domain :Activity ;\n"
			+ "                   rdfs:range xsd:string ;\n"
			+ "                   rdfs:label \"hidden description\" .\n"
			+ "\n"
			+ "\n"
			+ "###  https://auroral.iot.linkeddata.es/def/tourism#identifier\n"
			+ ":identifier rdf:type owl:DatatypeProperty ;\n"
			+ "            rdfs:domain :Activity ;\n"
			+ "            rdfs:range xsd:string ;\n"
			+ "            rdfs:label \"identifier\" .\n"
			+ "\n"
			+ "\n"
			+ "###  https://auroral.iot.linkeddata.es/def/tourism#isBookable\n"
			+ ":isBookable rdf:type owl:DatatypeProperty ;\n"
			+ "            rdfs:domain :Activity ;\n"
			+ "            rdfs:range xsd:boolean ;\n"
			+ "            rdfs:label \"is bookable\" .\n"
			+ "\n"
			+ "\n"
			+ "###  https://auroral.iot.linkeddata.es/def/tourism#longDescription\n"
			+ ":longDescription rdf:type owl:DatatypeProperty ;\n"
			+ "                 rdfs:domain :Activity ;\n"
			+ "                 rdfs:range xsd:string ;\n"
			+ "                 rdfs:label \"long description\" .\n"
			+ "\n"
			+ "\n"
			+ "###  https://auroral.iot.linkeddata.es/def/tourism#shortDescription\n"
			+ ":shortDescription rdf:type owl:DatatypeProperty ;\n"
			+ "                  rdfs:domain :Activity ;\n"
			+ "                  rdfs:range xsd:string ;\n"
			+ "                  rdfs:label \"short description\" .\n"
			+ "\n"
			+ "\n"
			+ "###  https://auroral.iot.linkeddata.es/def/tourism#startDate\n"
			+ ":startDate rdf:type owl:DatatypeProperty ;\n"
			+ "           rdfs:range xsd:date ;\n"
			+ "           rdfs:label \"start date\" .\n"
			+ "\n"
			+ "\n"
			+ "#################################################################\n"
			+ "#    Classes\n"
			+ "#################################################################\n"
			+ "\n"
			+ "###  http://purl.org/dc/terms/LinguisticSystem\n"
			+ "<http://purl.org/dc/terms/LinguisticSystem> rdf:type owl:Class ;\n"
			+ "                                            rdfs:label \"Linguistic System\" .\n"
			+ "\n"
			+ "\n"
			+ "###  http://www.w3.org/2003/01/geo/wgs84_pos#Point\n"
			+ "<http://www.w3.org/2003/01/geo/wgs84_pos#Point> rdf:type owl:Class ;\n"
			+ "                                                rdfs:label \"Point\" .\n"
			+ "\n"
			+ "\n"
			+ "###  http://xmlns.com/foaf/0.1/Image\n"
			+ "<http://xmlns.com/foaf/0.1/Image> rdf:type owl:Class ;\n"
			+ "                                  rdfs:label \"Image\" .\n"
			+ "\n"
			+ "\n"
			+ "###  https://auroral.iot.linkeddata.es/def/tourism#Activity\n"
			+ ":Activity rdf:type owl:Class, <http://jano.org/def#Root> ;\n"
			+ "          rdfs:subClassOf [ rdf:type owl:Restriction ;\n"
			+ "                            owl:onProperty :coverImage ;\n"
			+ "                            owl:cardinality \"1\"^^xsd:nonNegativeInteger\n"
			+ "                          ] ;\n"
			+ "          rdfs:label \"Activity\" .\n"
			+ "\n"
			+ "\n"
			+ "###  https://auroral.iot.linkeddata.es/def/tourism#ActivityDifficulty\n"
			+ ":ActivityDifficulty rdf:type owl:Class ;\n"
			+ "                    rdfs:subClassOf <https://www.w3.org/ns/org#Concept> ;\n"
			+ "                    rdfs:label \"Activity Difficulty\" .\n"
			+ "\n"
			+ "\n"
			+ "###  https://auroral.iot.linkeddata.es/def/tourism#Channel\n"
			+ ":Channel rdf:type owl:Class ;\n"
			+ "         rdfs:label \"Channel\" .\n"
			+ "\n"
			+ "\n"
			+ "###  https://auroral.iot.linkeddata.es/def/tourism#Currency\n"
			+ ":Currency rdf:type owl:Class ;\n"
			+ "          rdfs:label \"Currency\" .\n"
			+ "\n"
			+ "\n"
			+ "###  https://auroral.iot.linkeddata.es/def/tourism#Price\n"
			+ ":Price rdf:type owl:Class ;\n"
			+ "       rdfs:label \"Price\" .\n"
			+ "\n"
			+ "\n"
			+ "###  https://www.w3.org/ns/org#Concept\n"
			+ "<https://www.w3.org/ns/org#Concept> rdf:type owl:Class ;\n"
			+ "                                    rdfs:label \"Concept\" .\n"
			+ "\n"
			+ "\n"
			+ "#################################################################\n"
			+ "#    Individuals\n"
			+ "#################################################################\n"
			+ "\n"
			+ "###  https://auroral.iot.linkeddata.es/def/tourism#\n"
			+ "<https://auroral.iot.linkeddata.es/def/tourism#> rdf:type owl:NamedIndividual ;\n"
			+ "                                                 <http://purl.org/dc/terms/description> \"Ontology code created by Chowlk\" ;\n"
			+ "                                                 <http://purl.org/dc/terms/title> \"The AURORAL Tourism Ontology\" .\n"
			+ "\n"
			+ "\n"
			+ "###  https://auroral.iot.linkeddata.es/def/tourism#Easy\n"
			+ ":Easy rdf:type owl:NamedIndividual ,\n"
			+ "               :ActivityDifficulty .\n"
			+ "\n"
			+ "\n"
			+ "###  https://auroral.iot.linkeddata.es/def/tourism#Hard\n"
			+ ":Hard rdf:type owl:NamedIndividual ,\n"
			+ "               :ActivityDifficulty .\n"
			+ "\n"
			+ "\n"
			+ "###  https://auroral.iot.linkeddata.es/def/tourism#Medium\n"
			+ ":Medium rdf:type owl:NamedIndividual ,\n"
			+ "                 :ActivityDifficulty .\n"
			+ "\n"
			+ "\n"
			+ "###  https://auroral.iot.linkeddata.es/def/tourism#VeryEasy\n"
			+ ":VeryEasy rdf:type owl:NamedIndividual ,\n"
			+ "                   :ActivityDifficulty .\n"
			+ "\n"
			+ "\n"
			+ "###  https://auroral.iot.linkeddata.es/def/tourism#VeryHard\n"
			+ ":VeryHard rdf:type owl:NamedIndividual ,\n"
			+ "                   :ActivityDifficulty .\n"
			+ "\n"
			+ "\n"
			+ "###  Generated by the OWL API (version 5.1.14) https://github.com/owlcs/owlapi/";

	public static void main(String[] args) throws ReaderException {
		// https://jena.apache.org/documentation/ontology/#general-concepts

		TurtleAdapter adapter = new TurtleAdapter();

		adapter.adapt(model);
	}


}
